[package]
name = "otto-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
otto-protocol = { path = "../protocol" }
otto-engine = { path = "../engine" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
rustyline = "14"

[dev-dependencies]
uuid = { workspace = true }
